openapi: 3.0.1
info:
  description: APIs to manage and consume information about Carriers
  title: Noyo Carrier Carrier Mapped Field Carriers API
  version: 1.0.0
servers: []
tags:
- name: Carriers
paths:
  /api/v1/carriers:
    get:
      description: Returns a list of all Carriers matching an optional query by name, state, line of coverage, or list of IDs.
      operationId: queryCarrierPublicList
      parameters:
      - in: query
        name: state
        required: false
        schema:
          type: string
      - in: query
        name: internal_name
        required: false
        schema:
          type: string
      - in: query
        name: line_of_coverage
        required: false
        schema:
          type: string
      - in: query
        name: ids
        required: false
        schema:
          type: string
      - description: The unique identifier of the organization for which you would like to view carriers
        in: query
        name: organization_id
        required: false
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      - in: query
        name: is_listed
        required: false
        schema:
          type: boolean
      - in: query
        name: is_send
        required: false
        schema:
          type: boolean
      responses:
        '200':
          content:
            application/json:
              example:
              - display_name: Aetna
                id: 29189cfd-25e9-4d54-a630-9b3e1dafa1c9
                internal_name: Aetna
                lines_of_coverage:
                - medical
                - dental
                - vision
                - life-basic
                - life-voluntary
                - std-basic
                - ltd-basic
                state: AZ
                version: 16e0fbbd-bf45-4955-a0ab-3ec6a898c79b
              - display_name: Aetna
                id: 8fac0992-933a-4743-8dab-0d606ef2569e
                internal_name: Aetna
                lines_of_coverage:
                - medical
                - dental
                - vision
                - life-basic
                - life-voluntary
                - std-basic
                state: CA
                version: 5db1aefe-19de-463f-b19e-1c00be289ba8
              schema:
                items:
                  $ref: '#/components/schemas/CarrierResult'
                type: array
          description: A list of Carrier models
      summary: Query for list of matching carriers
      tags:
      - Carriers
  /api/v1/carriers/request:
    post:
      description: Create a new Organization Carrier Connection
      operationId: createPublicCarrier
      requestBody:
        content:
          application/json:
            examples:
              success:
                value:
                  carrier_id: 2ffb68e0-bcd2-499b-83ea-2c8d24df4ae5
                  estimated_volume: 2000
            schema:
              $ref: '#/components/schemas/CreateOrganizationCarrierPublicRequest'
        required: true
      responses:
        '201':
          content:
            application/json:
              example:
                carrier_id: 2ffb68e0-bcd2-499b-83ea-2c8d24df4ae5
                created: 1557862286
                estimated_volume: 2000
                id: e620170a-8a12-4ac2-ad5d-6148b910c049
                modified: 1557862286
                organization_id: c0d30398-4f94-48a8-8498-8983df07d036
                status: pending
                version: 47ab4c14-cf9d-4b2f-a7d9-cb41860d87fa
              schema:
                $ref: '#/components/schemas/OrganizationCarrierResult'
          description: Returns the new Organization Carrier connection
      summary: Create a new Organization Carrier Connection
      tags:
      - Carriers
  /api/v1/carriers/{carrier_id}:
    get:
      description: Returns the latest version of a single Carrier based on the ID provided
      operationId: getCarrier
      parameters:
      - in: path
        name: carrier_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                display_name: Aetna
                id: 8fac0992-933a-4743-8dab-0d606ef2569e
                internal_name: Aetna
                lines_of_coverage:
                - medical
                - dental
                - vision
                - life-basic
                - life-voluntary
                - std-basic
                state: CA
                version: 5db1aefe-19de-463f-b19e-1c00be289ba8
              schema:
                $ref: '#/components/schemas/CarrierResult'
          description: Get a single carrier by ID
      summary: Get a single carrier
      tags:
      - Carriers
components:
  schemas:
    OrganizationCarrierResult:
      properties:
        carrier_id:
          description: Carrier ID associated with the organization
          format: uuid
          readOnly: true
          type: string
        created:
          description: The date the record was created
          type: integer
          x-format: timestamp
        estimated_volume:
          description: Estimated number of enrollments with this carrier
          format: int32
          type: integer
        id:
          description: Unique identifier of the record in Noyo
          format: uuid
          type: string
        modified:
          description: The date the record was last updated
          type: integer
          x-format: timestamp
        organization_id:
          description: Unique identifier of the platform organization in Noyo
          format: uuid
          readOnly: true
          type: string
        status:
          description: Status of the organization carrier connection
          type: string
        version:
          description: Current version of the record
          format: uuid
          type: string
      required:
      - carrier_id
      - created
      - id
      - modified
      - organization_id
      - status
      - version
      type: object
      x-field_order:
      - id
      - version
      - created
      - modified
      - carrier_id
      - organization_id
      - status
      - estimated_volume
    CreateOrganizationCarrierPublicRequest:
      properties:
        carrier_id:
          description: Carrier ID associated with the organization
          format: uuid
          type: string
        estimated_volume:
          default: 0
          description: estimated number of enrollments with this carrier
          format: int32
          type: integer
      required:
      - carrier_id
      type: object
      x-field_order: []
    CarrierResult:
      properties:
        display_name:
          type: string
        id:
          format: uuid
          readOnly: true
          type: string
        internal_name:
          type: string
        is_send:
          description: Carrier has send connection
          readOnly: true
          type: boolean
        lines_of_coverage:
          items:
            enum:
            - medical
            - dental
            - vision
            - life-basic
            - life-voluntary
            - add-basic
            - add-voluntary
            - std-basic
            - std-voluntary
            - ltd-basic
            - ltd-voluntary
            - accident-basic
            - accident-voluntary
            - critical-illness-basic
            - critical-illness-voluntary
            - hospital-indemnity-basic
            - hospital-indemnity-voluntary
            type: string
          minItems: 1
          type: array
        state:
          enum:
          - AL
          - AK
          - AZ
          - AR
          - CA
          - CO
          - CT
          - DC
          - DE
          - FL
          - GA
          - HI
          - ID
          - IL
          - IN
          - IA
          - KS
          - KY
          - LA
          - ME
          - MD
          - MA
          - MI
          - MN
          - MS
          - MO
          - MT
          - NE
          - NV
          - NH
          - NJ
          - NM
          - NY
          - NC
          - ND
          - OH
          - OK
          - OR
          - PA
          - RI
          - SC
          - SD
          - TN
          - TX
          - US
          - UT
          - VT
          - VA
          - WA
          - WV
          - WI
          - WY
          type: string
        status:
          description: Status of the carrier at the organization
          readOnly: true
          type: string
        version:
          format: uuid
          readOnly: true
          type: string
      required:
      - display_name
      - id
      - internal_name
      - is_send
      - lines_of_coverage
      - state
      - version
      type: object
      x-field_order: []
