openapi: 3.0.1
info:
  description: APIs to manage and consume information about Carriers
  title: Noyo Carrier Carrier Mapped Field Discrepancies API
  version: 1.0.0
servers: []
tags:
- name: Discrepancies
paths:
  /api/v1/discrepancies:
    get:
      description: Returns a list of all discrepancies matching the given query
      operationId: getDiscrepancyList
      parameters:
      - description: The max size of each page of results
        in: query
        name: page_size
        required: false
        schema:
          type: integer
      - description: The integer offset at which to start the page. Possible values are 0 to total_records - 1
        in: query
        name: offset
        required: false
        schema:
          type: integer
      - description: Status of the discrepancies
        in: query
        name: status
        required: false
        schema:
          type: string
      - description: Status grouping of the discrepancies
        in: query
        name: status_grouping
        required: false
        schema:
          type: string
      - description: Type grouping of the discrepancies
        in: query
        name: type_grouping
        required: false
        schema:
          type: string
      - description: The unique identifier of the carrier for which you would like to view discrepancies
        in: query
        name: carrier_id
        required: false
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      - description: The unique identifier of the group for which you would like to view discrepancies
        in: query
        name: group_id
        required: false
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      - description: Unique identifier of the model that is the subject of the discrepancy
        in: query
        name: subject_id
        required: false
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      - description: The type of the model that is the subject of the discrepancy
        in: query
        name: subject_type
        required: false
        schema:
          type: string
      - description: The categorization of the discrepancy
        in: query
        name: discrepancy_type
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                meta:
                  offset: 0
                  page_num: 1
                  page_size: 20
                  total_records: 1
                response:
                - body:
                    carrier_value: '2020-01-01'
                    distributor_value: '2020-02-01'
                  carrier_id: 8fac0992-933a-4743-8dab-0d606ef2569e
                  context: ''
                  created: 1557862286
                  discrepancy_type: individual_enrollment_effective_start_date_mismatch
                  group_id: 436fb487-bb75-42d4-9651-7b1471a8940e
                  id: dd9a1813-34f7-4c7e-86bc-f041f2cbd9a1
                  modified: 1557862286
                  status: pending_resolution
                  subject_id: 7027d416-3bed-43e8-b824-508d9c0d323e
                  subject_type: IndividualEnrollment
                  version: ea38e798-cd61-4fa2-b485-d1c5b87a61af
              schema:
                $ref: '#/components/schemas/PaginatedDiscrepancyPublicResult'
          description: Successful Response - Returns all matching Discrepancies
      summary: List Discrepancies
      tags:
      - Discrepancies
  /api/v1/discrepancies/{discrepancy_id}:
    get:
      description: Returns the latest version of a single discrepancy based on the ID provided
      operationId: getDiscrepancy
      parameters:
      - description: The unique identifier of the discrepancy you would like to retrieve
        in: path
        name: discrepancy_id
        required: true
        schema:
          example: 30b74a44-d5b1-4123-a7a4-6d3aec251ba4
          format: uuid
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                body:
                  carrier_value: '2020-01-01'
                  distributor_value: '2020-02-01'
                carrier_id: 8fac0992-933a-4743-8dab-0d606ef2569e
                context: ''
                created: 1557862286
                discrepancy_type: individual_enrollment_effective_start_date_mismatch
                group_id: 436fb487-bb75-42d4-9651-7b1471a8940e
                id: dd9a1813-34f7-4c7e-86bc-f041f2cbd9a1
                modified: 1557862286
                status: pending_resolution
                subject_id: 7027d416-3bed-43e8-b824-508d9c0d323e
                subject_type: IndividualEnrollment
                version: ea38e798-cd61-4fa2-b485-d1c5b87a61af
              schema:
                $ref: '#/components/schemas/DiscrepancyPublicResult'
          description: Successful Response - Returns a single Discrepancy
      summary: Get Discrepancy
      tags:
      - Discrepancies
  /api/v1/discrepancies/{discrepancy_id}/ack:
    put:
      description: Acknowledge receipt of a discrepancy
      operationId: acknowledgeDiscrepancy
      parameters:
      - description: Unique identifier of the discrepancy in the Noyo system
        in: path
        name: discrepancy_id
        required: true
        schema:
          format: uuid
          type: string
      requestBody:
        content:
          application/json:
            examples:
              success:
                summary: An empty request, simply acknowledging discrepancy receipt
                value: null
            schema:
              $ref: '#/components/schemas/DiscrepancyAckRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                body:
                  carrier_value: '2020-01-01'
                  distributor_value: '2020-02-01'
                carrier_id: 8fac0992-933a-4743-8dab-0d606ef2569e
                context: ''
                created: 1557862286
                discrepancy_type: individual_enrollment_effective_start_date_mismatch
                group_id: 436fb487-bb75-42d4-9651-7b1471a8940e
                id: dd9a1813-34f7-4c7e-86bc-f041f2cbd9a1
                modified: 1557862286
                status: acknowledged
                subject_id: 7027d416-3bed-43e8-b824-508d9c0d323e
                subject_type: IndividualEnrollment
                version: ea38e798-cd61-4fa2-b485-d1c5b87a61af
              schema:
                $ref: '#/components/schemas/DiscrepancyPublicResult'
          description: Successful Response - Returns the updated Discrepancy
      summary: Acknowledge Discrepancy
      tags:
      - Discrepancies
  /api/v1/discrepancies/{discrepancy_id}/notes:
    x-summary: Get a list of discrepancy notes
    get:
      description: Returns a list of all notes for a given discrepancy.
      operationId: getDiscrepancyNotesList
      parameters:
      - description: The unique identifier of the discrepancy for which you would like to view notes
        in: path
        name: discrepancy_id
        required: true
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      - description: The max size of each page of results
        in: query
        name: page_size
        required: false
        schema:
          type: integer
      - description: The integer offset at which to start the page. Possible values are 0 to total_records - 1
        in: query
        name: offset
        required: false
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              example:
                meta:
                  offset: 0
                  page_num: 1
                  page_size: 20
                  total_records: 1
                response:
                - author_type: noyo
                  content: This discrepancy is associated with 5 others that will be sent over soon.
                  discrepancy_id: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
                  id: 30b74a44-d5b1-4123-a7a4-6d3aec251ba4
                  version: 6260146a-3486-4c3d-b2a6-fcd3f8c84043
              schema:
                $ref: '#/components/schemas/PaginatedDiscrepancyNoteResult'
          description: Successful Response - Returns all matching discrepancy notes
      summary: Get a list of all discrepancy notes under a single discrepancy
      tags:
      - Discrepancies
  /api/v1/discrepancies/{discrepancy_id}/request_outcome:
    x-summary: Request a particular discrepancy outcome
    put:
      description: Request a new outcome attempt for a discrepancy
      operationId: requestDiscrepancyOutcome
      parameters:
      - description: The unique identifier of the associated discrepancy
        in: path
        name: discrepancy_id
        required: true
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      requestBody:
        content:
          application/json:
            examples:
              success:
                summary: A discrepancy resolution body
                value:
                  distributor_action: will_update
                  outcome: distributor_change
                  request_context: After checking with the team, this looks like an issue on our end, will update
                  resolution_type: offline
            schema:
              $ref: '#/components/schemas/DiscrepancyResolutionRequestOutcome'
        required: true
      responses:
        '201':
          content:
            application/json:
              example:
                discrepancy_id: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
                distributor_action: will_update
                id: 30b74a44-d5b1-4123-a7a4-6d3aec251ba4
                outcome: distributor_change
                request_context: After checking with the team, this looks like an issue on our end, will update
                resolution_type: offline
                result: {}
                version: 6260146a-3486-4c3d-b2a6-fcd3f8c84043
              schema:
                $ref: '#/components/schemas/DiscrepancyResolutionResult'
          description: Successful Response - Returns the new Discrepancy Resolution
      summary: Request Discrepancy Outcome
      tags:
      - Discrepancies
  /api/v1/discrepancies/{discrepancy_id}/resolutions:
    x-summary: Get a list of discrepancy resolutions
    get:
      description: Returns a list of all resolutions for a given discrepancy.
      operationId: getDiscrepancyResolutionsList
      parameters:
      - description: The unique identifier of the discrepancy for which you would like to view resolutions
        in: path
        name: discrepancy_id
        required: true
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      - description: The max size of each page of results
        in: query
        name: page_size
        required: false
        schema:
          type: integer
      - description: The integer offset at which to start the page. Possible values are 0 to total_records - 1
        in: query
        name: offset
        required: false
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              example:
                meta:
                  offset: 0
                  page_num: 1
                  page_size: 20
                  total_records: 1
                response:
                - automated_change_id: bd957820-4652-4ee7-8a3a-6413df21e28d
                  automated_change_type: member_request
                  discrepancy_id: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
                  distributor_action: no_update
                  id: 30b74a44-d5b1-4123-a7a4-6d3aec251ba4
                  outcome: carrier_change
                  resolution_type: member_request
                  result:
                    context: Something here explaining the resolution
                    type: note
                  version: 6260146a-3486-4c3d-b2a6-fcd3f8c84043
              schema:
                $ref: '#/components/schemas/PaginatedDiscrepancyResolutionResult'
          description: Successful Response - Returns all matching discrepancy resolutions
      summary: Get a list of all discrepancy resolutions under a single discrepancy
      tags:
      - Discrepancies
  /ui/v1/discrepancies:
    get:
      description: Returns a list of all discrepancies matching the given query
      operationId: uiGetDiscrepancyList
      parameters:
      - description: The max size of each page of results
        in: query
        name: page_size
        required: false
        schema:
          type: integer
      - description: The integer offset at which to start the page. Possible values are 0 to total_records - 1
        in: query
        name: offset
        required: false
        schema:
          type: integer
      - description: Status of the discrepancies
        in: query
        name: status
        required: false
        schema:
          type: string
      - description: Status grouping of the discrepancies
        in: query
        name: status_grouping
        required: false
        schema:
          type: string
      - description: Type grouping of the discrepancies
        in: query
        name: type_grouping
        required: false
        schema:
          type: string
      - description: The unique identifier of the carrier for which you would like to view discrepancies
        in: query
        name: carrier_id
        required: false
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      - description: The unique identifier of the group for which you would like to view discrepancies
        in: query
        name: group_id
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      - description: Unique identifier of the model that is the subject of the discrepancy
        in: query
        name: subject_id
        required: false
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      - description: The type of the model that is the subject of the discrepancy
        in: query
        name: subject_type
        required: false
        schema:
          type: string
      - description: The categorization of the discrepancy
        in: query
        name: discrepancy_type
        required: false
        schema:
          type: string
      - description: The attribute on which to sort the discrepancies
        in: query
        name: sort_by
        required: false
        schema:
          type: string
      - description: Either asc or desc, to denote the data's direction
        in: query
        name: sort_direction
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                meta:
                  offset: 0
                  page_num: 1
                  page_size: 20
                  total_records: 1
                response:
                - discrepancy:
                    body:
                      carrier_value: '2020-01-01'
                      distributor_value: '2020-02-01'
                    carrier_id: 8fac0992-933a-4743-8dab-0d606ef2569e
                    context: ''
                    created: 1557862286
                    discrepancy_type: individual_enrollment_effective_start_date_mismatch
                    group_id: 436fb487-bb75-42d4-9651-7b1471a8940e
                    id: dd9a1813-34f7-4c7e-86bc-f041f2cbd9a1
                    modified: 1557862286
                    status: pending_resolution
                    subject_id: 7027d416-3bed-43e8-b824-508d9c0d323e
                    subject_type: IndividualEnrollment
                    version: ea38e798-cd61-4fa2-b485-d1c5b87a61af
                  employee:
                    employment:
                      employment_dates:
                        full_time_start: '2015-01-01'
                        hire_date: '2014-12-10'
                      employment_status: full-time
                      hours_worked: 50
                      occupation: Senior Analyst
                      salary:
                        amount: 55000
                        type: salary
                        unit: annual
                    group_id: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
                    id: 30b74a44-d5b1-4123-a7a4-6d3aec251ba4
                    location_id: bd957820-4652-4ee7-8a3a-6413df21e28d
                    person:
                      contact:
                        email_address: david@testemail.com
                        email_address_type: home
                        home_phone: '+12065551234'
                        preferred_method: email
                        work_phone: '+12065559876'
                      date_of_birth: '1981-06-22'
                      first_name: David
                      home_address:
                        city: San Francisco
                        county: San Francisco
                        state: CA
                        street_one: 1234 Home Ave
                        zip_code: '94107'
                      last_name: Johnson
                      marital_status: ''
                      sex: M
                      ssn: '123456789'
                    version: 6260146a-3486-4c3d-b2a6-fcd3f8c84043
                  group_plan:
                    carrier_id: c62a7be4-1551-4fb5-90c0-151121be785b
                    group_enrollment_id: 539b60cc-d9cb-4554-834d-e63a4f6a1c54
                    id: b988cd26-121a-4dd6-b0be-09399f6ecc0a
                    line_of_coverage: dental
                    name: PrettyNice Dental Plan
                  individual_enrollment:
                    cobra_enrollment: {}
                    effective_end_date: '2019-12-31'
                    effective_start_date: '2019-01-01'
                    enroll_data:
                      premium:
                        amount: 50
                        unit: Month
                    group_enrollment_id: 539b60cc-d9cb-4554-834d-e63a4f6a1c54
                    id: 7027d416-3bed-43e8-b824-508d9c0d323e
                    individual_enrollment_configuration: {}
                    individual_id: 30b74a44-d5b1-4123-a7a4-6d3aec251ba4
                    individual_type: employee
                    line_of_coverage: dental
                    plan_id: b988cd26-121a-4dd6-b0be-09399f6ecc0a
                    status: active
                    version: 27bbf929-78ca-4339-8bb3-39b75f92c4a4
              schema:
                $ref: '#/components/schemas/PaginatedDiscrepancyPublicResult'
          description: Successful Response - Returns all matching Discrepancies
      summary: List Discrepancies
      tags:
      - Discrepancies
  /ui/v1/discrepancies/{discrepancy_id}:
    get:
      description: Returns the latest version of a single discrepancy based on the ID provided
      operationId: uiGetDiscrepancy
      parameters:
      - in: path
        name: discrepancy_id
        required: true
        schema:
          format: uuid
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                body:
                  carrier_value: '2020-01-01'
                  distributor_value: '2020-02-01'
                carrier_id: 8fac0992-933a-4743-8dab-0d606ef2569e
                context: ''
                created: 1557862286
                discrepancy_type: individual_enrollment_effective_start_date_mismatch
                group_id: 436fb487-bb75-42d4-9651-7b1471a8940e
                id: dd9a1813-34f7-4c7e-86bc-f041f2cbd9a1
                modified: 1557862286
                status: pending_resolution
                subject_id: 7027d416-3bed-43e8-b824-508d9c0d323e
                subject_type: IndividualEnrollment
                version: ea38e798-cd61-4fa2-b485-d1c5b87a61af
              schema:
                $ref: '#/components/schemas/DiscrepancyPublicResult'
          description: Successful Response - Returns a single Discrepancy
      summary: Get Discrepancy
      tags:
      - Discrepancies
  /ui/v1/employees/{employee_id}/discrepancies:
    get:
      description: Returns a list of all discrepancies related to an employee, its dependents, and individual enrollments
      operationId: uiGetDiscrepanciesByEmployee
      parameters:
      - description: The unique identifier of the employee for which you would like to view discrepancies
        in: path
        name: employee_id
        required: true
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      - description: The max size of each page of results
        in: query
        name: page_size
        required: false
        schema:
          type: integer
      - description: The integer offset at which to start the page. Possible values are 0 to total_records - 1
        in: query
        name: offset
        required: false
        schema:
          type: integer
      - description: Status of the discrepancies
        in: query
        name: status
        required: false
        schema:
          type: string
      - description: Status grouping of the discrepancies
        in: query
        name: status_grouping
        required: false
        schema:
          type: string
      - description: Type grouping of the discrepancies
        in: query
        name: type_grouping
        required: false
        schema:
          type: string
      - description: The unique identifier of the carrier for which you would like to view discrepancies
        in: query
        name: carrier_id
        required: false
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      - description: Unique identifier of the model that is the subject of the discrepancy
        in: query
        name: subject_id
        required: false
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      - description: The type of the model that is the subject of the discrepancy
        in: query
        name: subject_type
        required: false
        schema:
          type: string
      - description: The categorization of the discrepancy
        in: query
        name: discrepancy_type
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                meta:
                  offset: 0
                  page_num: 1
                  page_size: 20
                  total_records: 1
                response:
                - discrepancy:
                    body:
                      carrier_value: '2020-01-01'
                      distributor_value: '2020-02-01'
                    carrier_id: 8fac0992-933a-4743-8dab-0d606ef2569e
                    created: 1557862286
                    discrepancy_type: individual_enrollment_effective_start_date_mismatch
                    group_id: 436fb487-bb75-42d4-9651-7b1471a8940e
                    id: dd9a1813-34f7-4c7e-86bc-f041f2cbd9a1
                    modified: 1557862286
                    notes: ''
                    status: pending_resolution
                    subject_id: 7027d416-3bed-43e8-b824-508d9c0d323e
                    subject_type: IndividualEnrollment
                    version: ea38e798-cd61-4fa2-b485-d1c5b87a61af
                  employee:
                    employment:
                      employment_dates:
                        full_time_start: '2015-01-01'
                        hire_date: '2014-12-10'
                      employment_status: full-time
                      hours_worked: 50
                      occupation: Senior Analyst
                      salary:
                        amount: 55000
                        type: salary
                        unit: annual
                    group_id: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
                    id: 30b74a44-d5b1-4123-a7a4-6d3aec251ba4
                    location_id: bd957820-4652-4ee7-8a3a-6413df21e28d
                    person:
                      contact:
                        email_address: david@testemail.com
                        email_address_type: home
                        home_phone: '+12065551234'
                        preferred_method: email
                        work_phone: '+12065559876'
                      date_of_birth: '1981-06-22'
                      first_name: David
                      home_address:
                        city: San Francisco
                        county: San Francisco
                        state: CA
                        street_one: 1234 Home Ave
                        zip_code: '94107'
                      last_name: Johnson
                      marital_status: ''
                      sex: M
                      ssn: '123456789'
                    version: 6260146a-3486-4c3d-b2a6-fcd3f8c84043
                  group_plan:
                    carrier_id: c62a7be4-1551-4fb5-90c0-151121be785b
                    group_enrollment_id: 539b60cc-d9cb-4554-834d-e63a4f6a1c54
                    id: b988cd26-121a-4dd6-b0be-09399f6ecc0a
                    line_of_coverage: dental
                    name: PrettyNice Dental Plan
                  individual_enrollment:
                    cobra_enrollment: {}
                    effective_end_date: '2019-12-31'
                    effective_start_date: '2019-01-01'
                    enroll_data:
                      premium:
                        amount: 50
                        unit: Month
                    group_enrollment_id: 539b60cc-d9cb-4554-834d-e63a4f6a1c54
                    id: 7027d416-3bed-43e8-b824-508d9c0d323e
                    individual_enrollment_configuration: {}
                    individual_id: 30b74a44-d5b1-4123-a7a4-6d3aec251ba4
                    individual_type: employee
                    line_of_coverage: dental
                    plan_id: b988cd26-121a-4dd6-b0be-09399f6ecc0a
                    status: active
                    version: 27bbf929-78ca-4339-8bb3-39b75f92c4a4
              schema:
                $ref: '#/components/schemas/PaginatedDiscrepancyPublicResult'
          description: Successful Response - Returns all matching Discrepancies for Employee
      summary: List Discrepancies Related to an Employee
      tags:
      - Discrepancies
components:
  schemas:
    DiscrepancyResolutionRequestOutcome:
      properties:
        distributor_action:
          description: The distributor action taken to sync up with Noyo's system, as a result of this change
          enum:
          - already_updated
          - will_update
          - no_update
          example: already_updated
          type: string
        outcome:
          description: The chosen response to take, after being notified of the discrepancy
          enum:
          - noyo_change
          - carrier_change
          - distributor_change
          - no_change
          example: carrier_value
          type: string
        request_context:
          description: Additional context to provide when requesting an outcome
          example: Our records reflect that they should be enrolled at the carrier, can you update?
          type: string
        resolution_type:
          description: The technique used to resolve the discrepancy
          enum:
          - member_request
          - offline
          - no_action
          example: offline
          type: string
      required:
      - outcome
      type: object
      x-field_order:
      - outcome
      - resolution_type
      - distributor_action
      - request_context
    DiscrepancyResolutionResult:
      properties:
        automated_change_id:
          description: Unique identifier of the associated automated change model
          format: uuid
          readOnly: true
          type: string
        automated_change_type:
          description: The type or model of the associated automated change, 'MemberRequest' or 'MemberSnapshot'
          enum:
          - member_request
          - member_snapshot
          - no_change
          readOnly: true
          type: string
        created:
          description: The date the record was created
          type: integer
        discrepancy_id:
          description: Unique identifier of the associated discrepancy
          format: uuid
          readOnly: true
          type: string
        distributor_action:
          description: The distributor action taken to sync up with Noyo's system, as a result of this change
          example: already_updated
          readOnly: true
          type: string
        id:
          description: Unique identifier of the record in Noyo
          format: uuid
          type: string
        modified:
          description: The date the record was last updated
          type: integer
        outcome:
          description: The outcome of the resolution, in order words, what change took place
          example: carrier_change
          readOnly: true
          type: string
        request_context:
          description: Additional context provided by the distributor when requesting an outcome
          example: Our records reflect that they should be enrolled at the carrier, can you update?
          readOnly: true
          type: string
        resolution_type:
          description: The technique used to resolve the discrepancy
          example: member_request
          readOnly: true
          type: string
        result:
          description: Result of the discrepancy resolution
          type: object
        version:
          description: Current version of the record
          format: uuid
          type: string
      required:
      - created
      - discrepancy_id
      - distributor_action
      - id
      - modified
      - request_context
      - resolution_type
      - version
      type: object
      x-field_order:
      - id
      - version
      - discrepancy_id
      - automated_change_id
      - automated_change_type
      - resolution_type
      - outcome
      - distributor_action
      - request_context
      - result
      - created
      - modified
    Meta:
      properties:
        offset:
          description: The offset of the first response record within the matching data set
          format: int32
          minimum: 0
          readOnly: true
          type: integer
        page_num:
          description: The page number of the response records within the overall data set (1-based integer)
          format: int32
          minimum: 1
          readOnly: true
          type: integer
        page_size:
          description: The maximum number of response records on each page of results
          format: int32
          minimum: 1
          readOnly: true
          type: integer
        total_records:
          description: The total number of records in the entire matching data set
          format: int32
          minimum: 0
          readOnly: true
          type: integer
      required:
      - offset
      - page_num
      - page_size
      type: object
    DiscrepancyPublicResult:
      properties:
        body:
          description: Details of what values are in contention with each other
          readOnly: true
          type: object
        carrier_id:
          description: Unique identifier of the associated carrier in Noyo
          format: uuid
          readOnly: true
          type: string
        context:
          description: Context for the processing of the discrepancy
          readOnly: true
          type: string
        created:
          description: The date the record was created
          type: integer
        discrepancy_type:
          description: Categorization of the discrepancy
          readOnly: true
          type: string
        group_id:
          description: Unique identifier of the group in Noyo
          format: uuid
          readOnly: true
          type: string
        id:
          description: Unique identifier of the record in Noyo
          format: uuid
          type: string
        modified:
          description: The date the record was last updated
          type: integer
        status:
          description: Status of the discrepancy
          enum:
          - needs_review
          - processing
          - resolved
          - dismissed
          - failed
          readOnly: true
          type: string
        subject_id:
          description: Unique identifier of the model that is the subject of the discrepancy
          format: uuid
          readOnly: true
          type: string
        subject_type:
          description: The type of the model that is the subject of the discrepancy
          readOnly: true
          type: string
        version:
          description: Current version of the record
          format: uuid
          type: string
      required:
      - body
      - carrier_id
      - created
      - discrepancy_type
      - group_id
      - id
      - modified
      - status
      - subject_id
      - subject_type
      - version
      type: object
      x-field_order:
      - id
      - version
      - group_id
      - carrier_id
      - status
      - discrepancy_type
      - subject_id
      - subject_type
      - context
      - body
      - created
      - modified
    DiscrepancyNoteResult:
      properties:
        author_type:
          description: A constant that describes whether the note is from noyo or the organization/distributor
          readOnly: true
          type: string
        content:
          description: Message regarding the discrepancy sent by noyo or the organization
          example: Our records reflect that they should be enrolled at the carrier, can you update?
          readOnly: true
          type: string
        created:
          description: The date the record was created
          type: integer
        discrepancy_id:
          description: Unique identifier of the associated discrepancy
          format: uuid
          readOnly: true
          type: string
        id:
          description: Unique identifier of the record in Noyo
          format: uuid
          type: string
        modified:
          description: The date the record was last updated
          type: integer
        version:
          description: Current version of the record
          format: uuid
          type: string
      required:
      - author_type
      - content
      - created
      - discrepancy_id
      - id
      - modified
      - version
      type: object
      x-field_order:
      - id
      - version
      - discrepancy_id
      - author_type
      - content
      - created
      - modified
    PaginatedDiscrepancyResolutionResult:
      properties:
        meta:
          allOf:
          - $ref: '#/components/schemas/Meta'
          description: Metadata associated with the response data
        response:
          description: List of discrepancy resolutions
          items:
            $ref: '#/components/schemas/DiscrepancyResolutionResult'
          type: array
      required:
      - meta
      - response
      type: object
      x-field_order:
      - meta
      - response
    DiscrepancyAckRequest:
      properties: {}
      type: object
      x-field_order: []
    PaginatedDiscrepancyPublicResult:
      properties:
        meta:
          allOf:
          - $ref: '#/components/schemas/Meta'
          description: Metadata associated with the response data
        response:
          description: List of discrepancy results
          items:
            $ref: '#/components/schemas/DiscrepancyPublicResult'
          type: array
      required:
      - meta
      - response
      type: object
      x-field_order:
      - meta
      - response
    PaginatedDiscrepancyNoteResult:
      properties:
        meta:
          allOf:
          - $ref: '#/components/schemas/Meta'
          description: Metadata associated with the response data
        response:
          description: List of discrepancy notes
          items:
            $ref: '#/components/schemas/DiscrepancyNoteResult'
          type: array
      required:
      - meta
      - response
      type: object
      x-field_order:
      - meta
      - response
