openapi: 3.0.1
info:
  description: APIs to manage and consume information about Carriers
  title: Noyo Carrier Carrier Mapped Field Group Connections API
  version: 1.0.0
servers: []
tags:
- name: Group Connections
paths:
  /api/v1/group_connections:
    get:
      description: Returns a list of all group connections.
      operationId: getGroupConnectionRequestList
      parameters:
      - description: The max size of each page of results
        in: query
        name: page_size
        required: false
        schema:
          type: integer
      - description: The integer offset at which to start the page. Possible values are 0 to total_records - 1
        in: query
        name: offset
        required: false
        schema:
          type: integer
      - description: Comma-separated list of requested Group Connection Request UUIDs
        in: query
        name: id
        required: false
        schema:
          type: string
      - description: Status of the group connection for which you would like to filter. Multiple statuses can be used, separated by a comma.
        in: query
        name: status
        schema:
          type: string
      - description: Comma-separated list of carrier UUID's for which you would like to view group connection requests
        in: query
        name: carrier_id
        required: false
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      - description: Used for filtering for a carrier-specific group ID. Must be used with a single carrier_id
        in: query
        name: carrier_group_id
        required: false
        schema:
          type: string
      - description: The unique identifier of the organization for which you would like to view group connection requests
        in: query
        name: organization_id
        required: false
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      - description: The attribute on which to sort the group connections
        in: query
        name: sort_by
        required: false
        schema:
          type: string
      - description: Either asc or desc, to denote the data's direction
        in: query
        name: sort_direction
        required: false
        schema:
          type: string
      - description: The actor type that requires a mapping action from
        in: query
        name: requires_mapping_action_from
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                meta:
                  offset: 0
                  page_num: 1
                  page_size: 20
                  total_records: 1
                response:
                - carrier_id: 8fac0992-933a-4743-8dab-0d606ef2569e
                  completed: 1557392400
                  created: 1557329939
                  group_data:
                    carrier_group_id: '10000000'
                    group_name: Test Company
                  id: dd9a1813-34f7-4c7e-86bc-f041f2cbd9a1
                  modified: 1557392400
                  organization_id: d61fa455-adf4-4dc4-8c57-6d779ba9475e
                  request_type: initial
                  status: processing
                  version: 9906b5d2-e76d-4bad-ba4c-8ce90b6b867b
              schema:
                $ref: '#/components/schemas/PaginatedGroupSetupRequestPublicResult'
          description: Successful Response - Returns all matching Group Connection Requests
      summary: List Group Connections
      tags:
      - Group Connections
    post:
      description: Create a new connection for a brand new group with a given carrier
      operationId: createGroupConnection
      requestBody:
        content:
          application/json:
            examples:
              success:
                value:
                  carrier_id: 8fac0992-933a-4743-8dab-0d606ef2569e
                  federal_ein: '123456789'
                  group_data:
                    carrier_group_id: '10000000'
                    group_name: Test Company
            schema:
              $ref: '#/components/schemas/GroupSetupRequestPublicAPICreateRequest'
        required: true
      responses:
        '201':
          content:
            application/json:
              example:
                carrier_id: 8fac0992-933a-4743-8dab-0d606ef2569e
                created: 1557329939
                group_data:
                  carrier_group_id: '10000000'
                  group_name: Test Company
                group_id: 47c07963-2e34-4da2-86b4-cbc3c57111c1
                id: dd9a1813-34f7-4c7e-86bc-f041f2cbd9a1
                modified: 1557329939
                organization_id: d61fa455-adf4-4dc4-8c57-6d779ba9475e
                request_type: initial
                status: created
                version: 9906b5d2-e76d-4bad-ba4c-8ce90b6b867b
              schema:
                $ref: '#/components/schemas/GroupSetupRequestPublicResult'
          description: Successful Response - Returns the new Group Connection
      summary: Create a new Group Connection
      tags:
      - Group Connections
  /api/v1/group_connections/{connection_id}:
    get:
      description: Returns the latest status of a single group connection based on the ID provided.
      operationId: getGroupConnection
      parameters:
      - description: The unique identifier of the group connection you would like to view
        in: path
        name: connection_id
        required: true
        schema:
          example: dd9a1813-34f7-4c7e-86bc-f041f2cbd9a1
          format: uuid
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                carrier_id: 8fac0992-933a-4743-8dab-0d606ef2569e
                completed: 1557392400
                created: 1557329939
                group_data:
                  carrier_group_id: '10000000'
                  group_name: Test Company
                group_id: 9e629e41-c706-4efd-9fbb-1ff2573fc67e
                id: dd9a1813-34f7-4c7e-86bc-f041f2cbd9a1
                modified: 1557392400
                organization_id: d61fa455-adf4-4dc4-8c57-6d779ba9475e
                request_type: initial
                setup_result: {}
                status: completed
                version: 9906b5d2-e76d-4bad-ba4c-8ce90b6b867b
              schema:
                $ref: '#/components/schemas/GroupSetupRequestPublicResult'
          description: Successful Response - Returns a single Group Connection
      summary: Get a single Group Connection
      tags:
      - Group Connections
  /api/v1/group_connections/{connection_id}/retry:
    put:
      description: Retry a carrier connection for an existing group
      operationId: retryGroupConnectionWithExistingGroup
      parameters:
      - description: The unique identifier of the group connection that needs to be reprocessed
        in: path
        name: connection_id
        required: true
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      requestBody:
        content:
          application/json:
            examples:
              success:
                value:
                  carrier_group_id: '10000001'
            schema:
              $ref: '#/components/schemas/GroupSetupRequestPublicAPIRetryRequest'
        required: true
      responses:
        '201':
          content:
            application/json:
              example:
                carrier_id: 8fac0992-933a-4743-8dab-0d606ef2569e
                created: 1667866198
                group_data:
                  carrier_group_id: '10000001'
                group_id: 47c07963-2e34-4da2-86b4-cbc3c57111c1
                id: 5e20ea6a-8027-464a-941a-867c115c846d
                modified: 1667866198
                organization_id: d61fa455-adf4-4dc4-8c57-6d779ba9475e
                request_type: incremental
                status: processing
                version: 608c6f37-5945-4987-b247-0b5acdf85034
              schema:
                $ref: '#/components/schemas/GroupSetupRequestPublicResult'
          description: Successful Response - Returns the updated Group Connection
      summary: Retry an existing group connection for an existing group
      tags:
      - Group Connections
  /api/v1/groups/{group_id}/group_connections:
    get:
      description: Returns a list of all group connections for a given group ID.
      operationId: getGroupConnectionRequestListByGroup
      parameters:
      - description: The unique identifier of the associated group in Noyo
        in: path
        name: group_id
        required: true
        schema:
          example: 2ce3b54a-2535-4803-b218-e6b44081d418
          format: uuid
          type: string
      - description: The max size of each page of results
        in: query
        name: page_size
        required: false
        schema:
          type: integer
      - description: The integer offset at which to start the page. Possible values are 0 to total_records - 1
        in: query
        name: offset
        required: false
        schema:
          type: integer
      - description: The attribute on which to sort the group connections
        in: query
        name: sort_by
        required: false
        schema:
          type: string
      - description: Either asc or desc, to denote the data's direction
        in: query
        name: sort_direction
        required: false
        schema:
          type: string
      - description: Status of group connection for which you would like to filter. Multiple statuses can be used, separated by a comma.
        in: query
        name: status
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                meta:
                  offset: 0
                  page_num: 1
                  page_size: 20
                  total_records: 1
                response:
                - carrier_id: 8fac0992-933a-4743-8dab-0d606ef2569e
                  completed: 1557392400
                  created: 1557329939
                  group_data:
                    carrier_group_id: '10000000'
                    group_name: Test Company
                  id: dd9a1813-34f7-4c7e-86bc-f041f2cbd9a1
                  modified: 1557392400
                  organization_id: d61fa455-adf4-4dc4-8c57-6d779ba9475e
                  request_type: initial
                  status: processing
                  version: 9906b5d2-e76d-4bad-ba4c-8ce90b6b867b
              schema:
                $ref: '#/components/schemas/PaginatedGroupSetupRequestPublicResult'
          description: Successful Response - Returns all matching Group Connection Requests
      summary: List Group Connections by Group
      tags:
      - Group Connections
    post:
      description: Create a new carrier connection for an existing group
      operationId: createGroupConnectionWithExistingGroup
      parameters:
      - description: The unique identifier of the group for which you would like to add a carrier connection
        in: path
        name: group_id
        required: true
        schema:
          example: 2613a221-d3c8-4c8a-86d5-e7e885fd1da9
          format: uuid
          type: string
      requestBody:
        content:
          application/json:
            examples:
              success:
                value:
                  carrier_id: 8fac0992-933a-4743-8dab-0d606ef2569e
                  group_data:
                    carrier_group_id: '10000000'
            schema:
              $ref: '#/components/schemas/GroupSetupRequestPublicAPINestedCreateRequest'
        required: true
      responses:
        '201':
          content:
            application/json:
              example:
                carrier_id: 8fac0992-933a-4743-8dab-0d606ef2569e
                created: 1557329939
                group_data:
                  carrier_group_id: '10000000'
                group_id: 47c07963-2e34-4da2-86b4-cbc3c57111c1
                id: dd9a1813-34f7-4c7e-86bc-f041f2cbd9a1
                modified: 1557329939
                organization_id: d61fa455-adf4-4dc4-8c57-6d779ba9475e
                request_type: incremental
                status: created
                version: 9906b5d2-e76d-4bad-ba4c-8ce90b6b867b
              schema:
                $ref: '#/components/schemas/GroupSetupRequestResult'
          description: Successful Response - Returns the new Group Connection
      summary: Create a new group connection in an existing group
      tags:
      - Group Connections
components:
  schemas:
    GroupSetupRequestPublicNestedGroupData:
      properties:
        broker_federal_ein:
          description: 'Brokerage or Organization Federal Employer Identification Number for the group''s broker. '
          example: '123123123'
          type: string
        broker_tin:
          description: Invidividual or DRLP Federal Tax Identification Number for the group's broker. Format can be either an EIN or SSN
          example: '123123123'
          type: string
        carrier_group_id:
          description: Unique identifier for the group in the carrier system
          minLength: 1
          type: string
        employer_email_address:
          description: Email address of the group's employer
          example: employer@example.com
          type: string
      required:
      - carrier_group_id
      type: object
      x-field_order:
      - carrier_group_id
      - broker_federal_ein
      - broker_tin
      - employer_email_address
    GroupSetupRequestPublicAPICreateRequest:
      properties:
        carrier_id:
          description: Unique identifier of the carrier in Noyo
          format: uuid
          type: string
        data_exchange_configuration:
          description: Use the specified data exchange configuration without calculating connection eligibility
          enum:
          - api
          - edi
          type: string
        federal_ein:
          description: Federal Employer Identification Number for the new group/company
          example: '123123123'
          type: string
        group_data:
          allOf:
          - $ref: '#/components/schemas/GroupSetupRequestPublicGroupData'
          description: Carrier-specific data to execute a group connection
        ignore_eligibility:
          description: Use the best available data exchange configuration without calculating connection eligibility
          type: boolean
      required:
      - carrier_id
      - group_data
      type: object
      x-field_order:
      - carrier_id
      - organization_id
      - federal_ein
      - group_data
    GroupSetupRequestPublicGroupDataResult:
      properties:
        broker_federal_ein:
          description: Broker federal EIN, used in Principal groups
          readOnly: true
          type: string
        broker_tin:
          description: Broker TIN, used in Anthem groups
          readOnly: true
          type: string
        carrier_group_id:
          description: Unique identifier for the group in the carrier system
          readOnly: true
          type: string
        employer_email_address:
          description: Email address of the group's employer
          readOnly: true
          type: string
        group_name:
          description: Name for the group in the Noyo system
          readOnly: true
          type: string
      required:
      - carrier_group_id
      - group_name
      type: object
    GroupSetupRequestPublicResult:
      properties:
        carrier_id:
          description: Unique identifier of the carrier in Noyo
          format: uuid
          readOnly: true
          type: string
        completed:
          description: Timestamp indicating when a group connection was marked as completed.
          readOnly: true
          type: integer
        created:
          description: The date the record was created
          type: integer
        federal_ein:
          description: Federal Employer Identification Number for the group
          readOnly: true
          type: string
        group_data:
          allOf:
          - $ref: '#/components/schemas/GroupSetupRequestPublicGroupDataResult'
          description: Carrier-specific data to execute a group connection
        group_id:
          description: ID of associated group model
          format: uuid
          readOnly: true
          type: string
        id:
          description: Unique identifier of the group connection in Noyo
          format: uuid
          readOnly: true
          type: string
        modified:
          description: The date the record was last updated
          type: integer
        organization_id:
          description: Unique identifier of the platform or broker organization in Noyo
          format: uuid
          readOnly: true
          type: string
        request_type:
          description: Type of the group connection
          readOnly: true
          type: string
        setup_result:
          description: More information about the result of the group connection
          readOnly: true
          type: object
        status:
          description: Status of the group connection
          enum:
          - created
          - processing
          - noyo_review
          - waiting_on_carrier
          - carrier_authorization
          - action_required
          - unable_to_connect
          - completed
          readOnly: true
          type: string
        version:
          description: Current version of the record
          format: uuid
          type: string
      required:
      - carrier_id
      - created
      - group_data
      - id
      - modified
      - organization_id
      - request_type
      - setup_metadata
      - setup_result
      - status
      - version
      type: object
      x-field_order:
      - id
      - version
      - created
      - modified
      - completed
      - organization_id
      - group_id
      - carrier_id
      - request_type
      - status
      - group_data
      - setup_result
      - federal_ein
    Meta:
      properties:
        offset:
          description: The offset of the first response record within the matching data set
          format: int32
          minimum: 0
          readOnly: true
          type: integer
        page_num:
          description: The page number of the response records within the overall data set (1-based integer)
          format: int32
          minimum: 1
          readOnly: true
          type: integer
        page_size:
          description: The maximum number of response records on each page of results
          format: int32
          minimum: 1
          readOnly: true
          type: integer
        total_records:
          description: The total number of records in the entire matching data set
          format: int32
          minimum: 0
          readOnly: true
          type: integer
      required:
      - offset
      - page_num
      - page_size
      type: object
    GroupSetupRequestPublicAPINestedCreateRequest:
      properties:
        carrier_id:
          description: Unique identifier of the carrier in Noyo
          format: uuid
          type: string
        data_exchange_configuration:
          description: Use the specified data exchange configuration without calculating connection eligibility
          enum:
          - api
          - edi
          type: string
        group_data:
          allOf:
          - $ref: '#/components/schemas/GroupSetupRequestPublicNestedGroupData'
          description: Carrier-specific data to execute a group connection
        ignore_eligibility:
          description: Use the best available data exchange configuration without calculating connection eligibility
          type: boolean
      required:
      - carrier_id
      - group_data
      type: object
      x-field_order:
      - carrier_id
      - group_data
      - setup_data
    GroupSetupRequestPublicAPIRetryRequest:
      properties:
        broker_federal_ein:
          description: 'Brokerage or Organization Federal Employer Identification Number for the group''s broker. '
          example: '123123123'
          type: string
        broker_tin:
          description: Invidividual or DRLP Federal Tax Identification Number for the group's broker. Format can be either an EIN or SSN
          example: '123123123'
          type: string
        carrier_group_id:
          description: Unique identifier for the group in the carrier system
          minLength: 1
          type: string
        employer_email_address:
          description: Email address of the group's employer
          example: employer@example.com
          type: string
        federal_ein:
          description: Federal Employer Identification Number for the new group/company
          example: '123123123'
          type: string
      type: object
      x-field_order: []
    GroupSetupRequestPublicGroupData:
      properties:
        broker_federal_ein:
          description: 'Brokerage or Organization Federal Employer Identification Number for the group''s broker. '
          example: '123123123'
          type: string
        broker_tin:
          description: Invidividual or DRLP Federal Tax Identification Number for the group's broker. Format can be either an EIN or SSN
          example: '123123123'
          type: string
        carrier_group_id:
          description: Unique identifier for the group in the carrier system
          minLength: 1
          type: string
        employer_email_address:
          description: Email address of the group's employer
          example: employer@example.com
          type: string
        group_name:
          description: Name for the group in the Noyo system
          minLength: 1
          type: string
      required:
      - carrier_group_id
      - group_name
      type: object
      x-field_order:
      - carrier_group_id
      - group_name
      - broker_federal_ein
      - broker_tin
      - employer_email_address
    GroupSetupRequestResult:
      properties:
        carrier_id:
          description: Unique identifier of the carrier in Noyo
          format: uuid
          readOnly: true
          type: string
        created:
          description: The date the record was created
          type: integer
        group_audit_request_id:
          description: ID of associated group audit request model
          format: uuid
          readOnly: true
          type: string
        group_data:
          description: Carrier-specific data required to execute a group connection
          readOnly: true
          type: object
        group_id:
          description: ID of associated group model
          format: uuid
          readOnly: true
          type: string
        id:
          description: Unique identifier of the group connection in Noyo
          format: uuid
          readOnly: true
          type: string
        modified:
          description: The date the record was last updated
          type: integer
        organization_id:
          description: Unique identifier of the platform or broker organization in Noyo
          format: uuid
          readOnly: true
          type: string
        request_type:
          description: Type of the group connection
          readOnly: true
          type: string
        setup_result:
          description: More information about the result of the group connection
          readOnly: true
          type: object
        status:
          description: Status of the group connection
          readOnly: true
          type: string
        version:
          description: Current version of the record
          format: uuid
          type: string
      required:
      - carrier_id
      - created
      - group_data
      - id
      - modified
      - organization_id
      - request_type
      - setup_data
      - setup_metadata
      - setup_result
      - status
      - version
      type: object
      x-field_order:
      - id
      - version
      - created
      - modified
      - organization_id
      - carrier_id
      - group_audit_request_id
      - group_id
      - request_type
      - status
      - group_data
      - setup_data
      - setup_result
      - sent_carrier_auth_comms
      - setup_metadata
    PaginatedGroupSetupRequestPublicResult:
      properties:
        meta:
          allOf:
          - $ref: '#/components/schemas/Meta'
          description: Metadata associated with the response data
        response:
          description: List of group connection results
          items:
            $ref: '#/components/schemas/GroupSetupRequestPublicResult'
          type: array
      required:
      - meta
      - response
      type: object
      x-field_order:
      - meta
      - response
